version: '2.1'

services:
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    odoo:
        build: .
        image: odoo:17.0
        restart: always
        volumes:
            - odoo_data:/var/lib/odoo:rw,z
            # for development purposes only
            - ${ODOO_ADDONS:-./}:/mnt/extra-addons:ro,z
            - ${ODOO_CONF:-./}:/etc/odoo:ro,z
        ports:
            # publish only and let Gitlab CI pick up the public port
#            - "${ODOO_PORT:-8070}"
            - "8017:8069"
        depends_on:
            - db
volumes:
    pgsql_data:
    odoo_data:
    odoo_addons:
